// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/mcp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_mcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{0}
}

type CrioConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrioConfigResponse) Reset() {
	*x = CrioConfigResponse{}
	mi := &file_proto_mcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrioConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrioConfigResponse) ProtoMessage() {}

func (x *CrioConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrioConfigResponse.ProtoReflect.Descriptor instead.
func (*CrioConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{1}
}

func (x *CrioConfigResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type RuntimeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeStatusResponse) Reset() {
	*x = RuntimeStatusResponse{}
	mi := &file_proto_mcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeStatusResponse) ProtoMessage() {}

func (x *RuntimeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeStatusResponse.ProtoReflect.Descriptor instead.
func (*RuntimeStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{2}
}

func (x *RuntimeStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    string                 `protobuf:"bytes,1,opt,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainersResponse) Reset() {
	*x = ContainersResponse{}
	mi := &file_proto_mcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainersResponse) ProtoMessage() {}

func (x *ContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainersResponse.ProtoReflect.Descriptor instead.
func (*ContainersResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{3}
}

func (x *ContainersResponse) GetContainers() string {
	if x != nil {
		return x.Containers
	}
	return ""
}

type ContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerRequest) Reset() {
	*x = ContainerRequest{}
	mi := &file_proto_mcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRequest) ProtoMessage() {}

func (x *ContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerRequest.ProtoReflect.Descriptor instead.
func (*ContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ContainerInspectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          string                 `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInspectResponse) Reset() {
	*x = ContainerInspectResponse{}
	mi := &file_proto_mcp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInspectResponse) ProtoMessage() {}

func (x *ContainerInspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInspectResponse.ProtoReflect.Descriptor instead.
func (*ContainerInspectResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerInspectResponse) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type ContainerStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuUsageUsec     uint64                 `protobuf:"varint,1,opt,name=cpu_usage_usec,json=cpuUsageUsec,proto3" json:"cpu_usage_usec,omitempty"`
	MemoryUsageBytes uint64                 `protobuf:"varint,2,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContainerStatsResponse) Reset() {
	*x = ContainerStatsResponse{}
	mi := &file_proto_mcp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatsResponse) ProtoMessage() {}

func (x *ContainerStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatsResponse.ProtoReflect.Descriptor instead.
func (*ContainerStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerStatsResponse) GetCpuUsageUsec() uint64 {
	if x != nil {
		return x.CpuUsageUsec
	}
	return 0
}

func (x *ContainerStatsResponse) GetMemoryUsageBytes() uint64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

type ContainerConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerConfigResponse) Reset() {
	*x = ContainerConfigResponse{}
	mi := &file_proto_mcp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerConfigResponse) ProtoMessage() {}

func (x *ContainerConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerConfigResponse.ProtoReflect.Descriptor instead.
func (*ContainerConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_mcp_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerConfigResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

var File_proto_mcp_proto protoreflect.FileDescriptor

const file_proto_mcp_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/mcp.proto\x12\x03mcp\"\a\n" +
	"\x05Empty\",\n" +
	"\x12CrioConfigResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\"/\n" +
	"\x15RuntimeStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"4\n" +
	"\x12ContainersResponse\x12\x1e\n" +
	"\n" +
	"containers\x18\x01 \x01(\tR\n" +
	"containers\"\"\n" +
	"\x10ContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x18ContainerInspectResponse\x12\x12\n" +
	"\x04info\x18\x01 \x01(\tR\x04info\"l\n" +
	"\x16ContainerStatsResponse\x12$\n" +
	"\x0ecpu_usage_usec\x18\x01 \x01(\x04R\fcpuUsageUsec\x12,\n" +
	"\x12memory_usage_bytes\x18\x02 \x01(\x04R\x10memoryUsageBytes\"1\n" +
	"\x17ContainerConfigResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config2\x93\x03\n" +
	"\n" +
	"MCPService\x124\n" +
	"\rGetCrioConfig\x12\n" +
	".mcp.Empty\x1a\x17.mcp.CrioConfigResponse\x12:\n" +
	"\x10GetRuntimeStatus\x12\n" +
	".mcp.Empty\x1a\x1a.mcp.RuntimeStatusResponse\x125\n" +
	"\x0eListContainers\x12\n" +
	".mcp.Empty\x1a\x17.mcp.ContainersResponse\x12H\n" +
	"\x10InspectContainer\x12\x15.mcp.ContainerRequest\x1a\x1d.mcp.ContainerInspectResponse\x12G\n" +
	"\x11GetContainerStats\x12\x15.mcp.ContainerRequest\x1a\x1b.mcp.ContainerStatsResponse\x12I\n" +
	"\x12GetContainerConfig\x12\x15.mcp.ContainerRequest\x1a\x1c.mcp.ContainerConfigResponseB-Z+github.com/harche/crio-mcp-server/pkg/protob\x06proto3"

var (
	file_proto_mcp_proto_rawDescOnce sync.Once
	file_proto_mcp_proto_rawDescData []byte
)

func file_proto_mcp_proto_rawDescGZIP() []byte {
	file_proto_mcp_proto_rawDescOnce.Do(func() {
		file_proto_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mcp_proto_rawDesc), len(file_proto_mcp_proto_rawDesc)))
	})
	return file_proto_mcp_proto_rawDescData
}

var file_proto_mcp_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_mcp_proto_goTypes = []any{
	(*Empty)(nil),                    // 0: mcp.Empty
	(*CrioConfigResponse)(nil),       // 1: mcp.CrioConfigResponse
	(*RuntimeStatusResponse)(nil),    // 2: mcp.RuntimeStatusResponse
	(*ContainersResponse)(nil),       // 3: mcp.ContainersResponse
	(*ContainerRequest)(nil),         // 4: mcp.ContainerRequest
	(*ContainerInspectResponse)(nil), // 5: mcp.ContainerInspectResponse
	(*ContainerStatsResponse)(nil),   // 6: mcp.ContainerStatsResponse
	(*ContainerConfigResponse)(nil),  // 7: mcp.ContainerConfigResponse
}
var file_proto_mcp_proto_depIdxs = []int32{
	0, // 0: mcp.MCPService.GetCrioConfig:input_type -> mcp.Empty
	0, // 1: mcp.MCPService.GetRuntimeStatus:input_type -> mcp.Empty
	0, // 2: mcp.MCPService.ListContainers:input_type -> mcp.Empty
	4, // 3: mcp.MCPService.InspectContainer:input_type -> mcp.ContainerRequest
	4, // 4: mcp.MCPService.GetContainerStats:input_type -> mcp.ContainerRequest
	4, // 5: mcp.MCPService.GetContainerConfig:input_type -> mcp.ContainerRequest
	1, // 6: mcp.MCPService.GetCrioConfig:output_type -> mcp.CrioConfigResponse
	2, // 7: mcp.MCPService.GetRuntimeStatus:output_type -> mcp.RuntimeStatusResponse
	3, // 8: mcp.MCPService.ListContainers:output_type -> mcp.ContainersResponse
	5, // 9: mcp.MCPService.InspectContainer:output_type -> mcp.ContainerInspectResponse
	6, // 10: mcp.MCPService.GetContainerStats:output_type -> mcp.ContainerStatsResponse
	7, // 11: mcp.MCPService.GetContainerConfig:output_type -> mcp.ContainerConfigResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mcp_proto_init() }
func file_proto_mcp_proto_init() {
	if File_proto_mcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mcp_proto_rawDesc), len(file_proto_mcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mcp_proto_goTypes,
		DependencyIndexes: file_proto_mcp_proto_depIdxs,
		MessageInfos:      file_proto_mcp_proto_msgTypes,
	}.Build()
	File_proto_mcp_proto = out.File
	file_proto_mcp_proto_goTypes = nil
	file_proto_mcp_proto_depIdxs = nil
}
